---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:
    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Check if SELinux is enabled
      command: getenforce
      register: selinux_status
      ignore_errors: true
      changed_when: false

    - name: Temporarily set SELinux to permissive mode 
      command: setenforce 0
      when: selinux_status.stdout != "Disabled"
      ignore_errors: true

    - name: Permanently disable SELinux in the config file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'

    - name: Temporarily disable swap
      command: swapoff -a

    - name: Permanently disable swap
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        line: '#\1'
        backrefs: yes
        state: present
        backup: yes

    - name: Create k8s.conf file in /etc/sysctl.d
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          vm.swappiness = 0

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
    
    - name: Check if br_netfilter module is loaded
      shell: lsmod | grep br_netfilter
      register: br_netfilter_status

    - name: Display br_netfilter status
      debug:
        msg: "{{ br_netfilter_status.stdout }}"

    - name: Start chronyd service
      systemd:
        name: chronyd
        state: started

    - name: Enable chronyd service to start on boot
      systemd: 
        name: chronyd
        enabled: yes

    - name: Install ipset and ipvsadm
      yum:
        name: 
          - ipset 
          - ipvsadm
        state: present

    - name: Ensure /etc/sysconfig/modules directory exists
      file:
        path: /etc/sysconfig/modules
        state: directory
        mode: '0755'

    - name: Create ipvs.modules file in /etc/sysconfig/modules/
      copy:
        dest: /etc/sysconfig/modules/ipvs.modules
        content: |
          #!/bin/bash
          modprobe -- ip_vs
          modprobe -- ip_vs_rr
          modprobe -- ip_vs_wrr
          modprobe -- ip_vs_sh
          modprobe -- nf_conntrack
    
    - name: Ensure ipvs.modules file is executable
      file: 
        path: /etc/sysconfig/modules/ipvs.modules
        mode: '0755'
        state: file
      
    - name: Load IPVS modules 
      command: /etc/sysconfig/modules/ipvs.modules

    - name: Check if IPVS and nf_conntrack modules are loaded
      shell: lsmod | grep -e ip_vs -e nf_conntrack
      register: ipvs_modules_status

    - name: Display IPVS modules status
      debug:
        msg: "{{ ipvs_modules_status.stdout }}"

    - name: Ensure /etc/rc.d/rc.local is executable
      file:
        path: /etc/rc.d/rc.local
        mode: '0755'
        state: file
