---
- name: "106"
  hosts: all
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:  
    - name: Ensure /etc/containerd exists
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Create default /etc/containerd/config.toml 
      command: containerd config default > /etc/containerd/config.toml 

    - name: Enable and start containerd
      systemd:
        name: containerd
        state: restarted
        
    - name: Enable and start kubelet
      systemd:
        name: kubelet
        state: restarted

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started
  