---
- name: "107"
  hosts: master1
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:  
    - name: Initialize Kubernetes cluster
      command: kubeadm init --apiserver-advertise-address=192.168.0.101 --pod-network-cidr=192.168.1.0/24 --service-cidr=192.168.2.0/24
        
# \
# # --control-plane-endpoint=loc-k8s-endpoint \
# # --cri-socket=/var/run/containerd/containerd.sock \
# # --apiserver-advertise-address=192.168.0.3 \
# # --pod-network-cidr=172.16.100.0/24 \
# # --service-cidr=172.16.0.0/24
# kubeadm init --control-plane-endpoint=loc-k8s-endpoint --cri-socket=/var/run/containerd/containerd.sock --apiserver-advertise-address=192.168.0.3 --pod-network-cidr=172.16.100.0/24 --service-cidr=172.16.0.0/24
# ssh master1 -o StrictHostKeyChecking=no
