---

- hosts: master1
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:
    - name: Set the hostname
      hostname:
        name: loc-k8s-master1

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: '127.0.1.1 loc-k8s-master1'
        create: yes

- hosts: worker1
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:
    - name: Set the hostname
      hostname:
        name: loc-k8s-worker1

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: '127.0.1.1 loc-k8s-worker1'
        create: yes

- hosts: worker2
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
    - vars.yaml
  tasks:
    - name: Set the hostname
      hostname:
        name: "{{ host_names[0] }}"

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: '127.0.1.1 loc-k8s-worker2'
        create: yes

- hosts: worker3
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:
    - name: Set the hostname
      hostname:
        name: loc-k8s-worker3

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: '127.0.1.1 loc-k8s-worker3'
        create: yes

- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:
    - name: Ensure /etc/hosts entries
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ item }}"
      with_items:
        - "192.168.0.101 loc-k8s-master1 "
        - "192.168.0.102 loc-k8s-worker1 "
        - "192.168.0.103 loc-k8s-worker2 "
        - "192.168.0.104 loc-k8s-worker3 "

    - name: Reboot
      reboot:
        msg: "Reboot initiated by Ansible"

    - name: Wait for the reboot to complete
      pause:
        seconds: 10

    - name: Re-establish connection after reboot
      meta: reset_connection