apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
data:
  nextcloud-password: a2Fpbm9zCg==
  mysql-password: a2Fpbm9zCg==
  mysql-root-password: a2Fpbm9zCg==