---
- name: "103"
  hosts: all
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yaml
  tasks:

    - name: Fetch containerd service file content
      uri:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        return_content: yes
      register: containerd_service_content

    - name: Ensure systemd service directory exists
      file:
        path: /usr/local/lib/systemd/system
        state: directory
        mode: '0755'

    - name: Write containerd service file to system directory
      copy:
        dest: /usr/local/lib/systemd/system/containerd.service
        content: "{{ containerd_service_content.content }}"
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started
